[package]
name = "deduplicator"
version = "0.1.6"
edition = "2021"
description = "find,filter,delete Duplicates"
license = "MIT"
authors = [
    "Sreedev Kodichath <sreedevpadmakumar@gmail.com>",
    "Valentin Bersier <vbersier@gmail.com>",
    "Dhruva Sagar <dhruva.sagar@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bytesize = "1.1.0"
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
colored = "2.0.0"
dashmap = { version = "5.4.0", features = ["rayon"] }
fxhash = "0.2.1"
globwalk = "0.8.1"
indicatif = { version = "0.17.2", features = ["rayon", "tokio"] }
itertools = "0.10.5"
memmap2 = "0.5.8"
prettytable-rs = "0.10.0"
rayon = "1.6.1"
thiserror = "1.0.38"
tokio = { version = "1.23.1", features = ["full"] }
unicode-segmentation = "1.10.0"
